unifiexporter:
  image: visago/unifi_exporter
  restart: 'always'
  ports:
    - '9130:9130'
  command: "-unifi.addr=https://192.168.1.1:8443/ -unifi.insecure=true -unifi.username=admin -unifi.password=password"
